### ISSUE TITLE
Mod causes GL ERROR spam in logs.

### ISSUE THREAD

**Issue by Kichura** [Provismet/Tooltip-Scroll-Fabric#13]
When using this mod to try and scroll anywhere including the title screen, it will cause errors to be spammed in logs over and over again until mod is disabled, i believe this has to do something with the keybinding system being badly set up.

First error *(anywhere)*:

```
[Render thread/ERROR]: ########## GL ERROR ##########
[Render thread/ERROR]: @ Render
[Render thread/ERROR]: 65539: Invalid key -1
```

Second error *(controls only, happens once iirc)*:

```
[Render thread/ERROR]: ########## GL ERROR ##########
[Render thread/ERROR]: @ Render
[Render thread/ERROR]: 65540: Invalid scancode -1
```

**Comment by Provismet** [comment]
Could you confirm what version of the mod you are using? I've encountered this problem before but I thought I had resolved it.

**Comment by Kichura** [comment]
I was able to reproduce on v1.2.2 of this mod via both 1.19.2 and 1.19.3.

**Comment by Provismet** [comment]
Thank you, I've pushed a fix that solves the problem.  
I assume that on your keybinds "horizontal move" was unbound? I've added a check for that and will update the releases once I resolve the other issue.
