### ISSUE TITLE
Tooltip background is broken on 1.19.4

### ISSUE THREAD

**Issue by Kichura** [Provismet/Tooltip-Scroll-Fabric#17]
### Type of Error

Incorrect Behaviour

### Description

Tooltip background breaks when continuing to scroll after hitting bottom, This was tested with creative mode but unsure if it also happens in survival.

### Mod Version

1.19.3-1.2.3

### Minecraft Version

1.19.4 (Latest)

### Mod Loader

Fabric

### Steps to Reproduce

```bash
1. Hover any item and scroll to bottom,
2. Continue scrolling even if there is nothing else to find anymore,
3. Watch the tooltip background break.
```

### Crash Log

```bash
(No crashes happened here)
```

**Comment by Provismet** [comment]
Can you upload a screenshot of this behaviour? I tried it myself and the error I see triggers differently to what you described. When I scroll, the background border moves instead, with no change when the tooltip hits the bottom of the screen.  

Attempting to scroll down.
![image](https://user-images.githubusercontent.com/17149901/229233387-b654f46d-5aba-4242-9e1f-f6a9b167563c.png)  

Attempting to scroll up.
![image](https://user-images.githubusercontent.com/17149901/229233531-65720a21-f0e3-42e5-ba17-9dab4f5403f2.png)  

I suspect Mojang added a new variable to the tooltip renderer and this made my stuff have the wrong offset; will be able to fix it when Gradle starts playing nicely and gives me the new source code.

**Comment by Kichura** [comment]
> Can you upload a screenshot of this behaviour? I tried it myself and the error I see triggers differently to what you described. When I scroll, the background border moves instead, with no change when the tooltip hits the bottom of the screen.
> 
> Attempting to scroll down. ![image](https://user-images.githubusercontent.com/17149901/229233387-b654f46d-5aba-4242-9e1f-f6a9b167563c.png)
> 
> Attempting to scroll up. ![image](https://user-images.githubusercontent.com/17149901/229233531-65720a21-f0e3-42e5-ba17-9dab4f5403f2.png)
> 
> I suspect Mojang added a new variable to the tooltip renderer and this made my stuff have the wrong offset; will be able to fix it when Gradle starts playing nicely and gives me the new source code.

Yeah that is the one i managed to produce including in creative mode pages, also gradle 7.5.1 should work for now as it doesn't crash the client easily.

**Comment by Provismet** [comment]
> also gradle 7.5.1 should work for now as it doesn't crash the client easily  

Oh no it's not client crashes, I just get weird gradle errors whenever I try to generate sources.
