### ISSUE TITLE
[Update Request] 1.18.1

### ISSUE THREAD

**Issue by Julienraptor01** [Provismet/Tooltip-Scroll-Fabric#2]
Hello, 
I like this thing but could you make it for minecraft 1.18.1 pls.
Thanks

**Comment by Texbio** [comment]
BUMP



same

**Comment by moehreag** [comment]
The author does not seem to support their mod anymore, but there are multiple people who have already forked and updated it. 

See https://github.com/moehreag/Tooltip-Scroll-Fabric/tree/1.18
or https://github.com/turtletowerz/Tooltip-Scroll-Fabric/tree/1.18 (probably better)

**Comment by Julienraptor01** [comment]
@moehreag yes but none of them has release and i don't want to have to compile it myself.

**Comment by moehreag** [comment]
Here is a compiled version of my fork (I tested it but still, no warranty that it works with your mod setup)
[tooltip-scroll-1.0.2.jar.zip](https://github.com/Provismet/Tooltip-Scroll-Fabric/files/8089825/tooltip-scroll-1.0.2.jar.zip)
(github doesn't want to have .jar files uploaded, so just remove the extra .zip)

**Comment by Julienraptor01** [comment]
I'm going to try it thanks

**Comment by Julienraptor01** [comment]
@moehreag thanks for your version it works great 👍

**Comment by Julienraptor01** [comment]
@moehreag @turtletowerz
does any of you two have planned to update your forks on 1.18.2 and further ?

**Comment by moehreag** [comment]
The mod works as-as in 1.18.2

**Comment by turtletowerz** [comment]
> @moehreag @turtletowerz does any of you two have planned to update your forks on 1.18.2 and further ? If no one of you plan to do it then i will try to quickly learn how to update mods and try to keep the mod updated on like curseforge and modrinth.

As moehreag mentioned, there should be no changes between 1.18.1 and 1.18.2 regarding the mod's usability. I've been considering moving this project into its own repo instead of a fork to work on releases and allow issues to be opened there instead of here, but that's for a future date.

**Comment by srnyx** [comment]
Now 1.19

**Comment by turtletowerz** [comment]
Decided to publish a jar in each version to make this easier so if you'd like a mod that should work with 1.19 download the jar file [here](https://github.com/turtletowerz/Tooltip-Scroll-Fabric/releases/tag/v1.1.2) and place it in your mods folder.

**Comment by srnyx** [comment]
> I've been considering moving this project into its own repo instead of a fork to work on releases and allow issues to be opened there instead of here, but that's for a future date.

Yes, please do that! And since the mod is MIT License, I think that would allow you to create a project on CurseForge (maybe called Tooltip Scroll 2 or Tooltip Scroll Next) **and** Modrinth.

**Comment by Provismet** [comment]
I've updated the mod to 1.18.2 and 1.19 now.
