### ISSUE TITLE
Scroll works with different actions

### ISSUE THREAD

**Issue by Disketaa** [Provismet/Tooltip-Scroll-Fabric#26]
### Type of Error

Incorrect Behaviour

### Description

![Scroll](https://github.com/user-attachments/assets/1a9b08d3-5ffb-466c-85ae-a8eb660957ba)

### Mod Version

1.4.0

### Minecraft Version

1.21.1

### Mod Loader

Fabric

### Steps to Reproduce

Open creative search
Hover on hotbar item
Scroll

Open creative search
Hover on item
Type "wasd"

**Comment by Provismet** [comment]
This isn't really a bug exactly, it's a known issue caused by menu screens being somewhat awkward to track. If scrolling inventories cause issues, then you can use keybinds (not WASD) to scroll - it's actually why that option exists.
