### ISSUE TITLE
Tooltip position does not save

### ISSUE THREAD

**Issue by paulwsully** [Provismet/Tooltip-Scroll-Fabric#27]
### Type of Error

Incorrect Behaviour

### Description

**Observed Behavior:**
When toggling the `Reset Position When Not Hovered` to `false`, the position will save, so long as you don't hover another item. Displaying any new tooltip will reset the position of the tooltip you previously moved.

**Expected Behavior:**
Moving the position of any tooltip should save the position of the tooltip for that item, regardless of what slot it's in or what other tooltips you have hovered.

**Extra Info:**
I do not currently have any other mod installed in my main world that would impact tooltips in any way. I have also tested this in a clean profile with only `Fabric API 0.92.2+1.20.1`, `Mod Menu 7.2.2`, and `Tooltip Scroll 1.3.0` enabled, with the same results observed.

If this is intended behavior, then I'd like to request a feature that indeed allows the behavior described in the expected behavior. Ideally, I would think that it would apply globally and have all tooltips be generated in the position set.

Regardless, great mod. Such a great quality of life being able to move tooltips at all. Thank you for the hard work on this!

### Mod Version

1.3.0

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

1) Toggle `Reset Position When Not Hovered` to `false`.
2) Scroll any tooltip.
3) Without hovering a different item, move the cursor away from the item with the adjusted tooltip.
4) Hover back over said item and the tooltip should have remained where it was adjusted to previously.
5) Now, hover over a different item. Notice the tooltip is unadjusted.
6) Hover back over the original item with the adjusted tooltip. Notice the tooltip has reset.

**Comment by Provismet** [comment]
What you are observing is the intended behaviour. The mod only (optionally) remembers the tooltip position of the previously displayed tooltip.  
It would be infeasible to save every tooltip position, tooltips are not actually tied to item slots; GUI buttons and the in-game chat use the exact same tooltips too.

**Comment by paulwsully** [comment]
Fair enough!

I'll have to give a crack at making the functionality sometime then. I appreciate the response!
