### ISSUE TITLE
incompat and crash with extra alchemy

### ISSUE THREAD

**Issue by spaghettube** [Provismet/Tooltip-Scroll-Fabric#9]
crashes whenever i hover over a potion (only on the latest version, 1.2.0 works fine)
[crash-2022-12-22_23.33.04-client.txt](https://github.com/Provismet/Tooltip-Scroll-Fabric/files/10290961/crash-2022-12-22_23.33.04-client.txt)
not enough crashes:
[crash-2022-12-22_23.38.15-client.txt](https://github.com/Provismet/Tooltip-Scroll-Fabric/files/10290962/crash-2022-12-22_23.38.15-client.txt)

**Comment by Provismet** [comment]
I've just pushed a fix which solves the problem.  
Just note that potion rings won't have their tooltip positions reset when hovering onto different potion rings though. They appear to be a special case and don't use text components in their tooltip. Potions themselves should be fine now though.
